# Generated by Django 4.0.5 on 2022-07-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('author', models.CharField(max_length=128)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
