# Generated by Django 4.0.5 on 2023-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
    ]
